name: Test

on:
  push:
    branches:
      - backend/01-initialize
  pull_request:
    branches:
      - main
      - backend/01-initialize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.13
    - name: Change working directory
      run: cd server/user
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests using Mocha
      run: npm test -- --reporter=spec --testPathPattern='mocha tests/**/*.test.js'
