name: Test

on:
  pull_request:
    branches:
      - main
      - backend/development

jobs:
  test-orchestrator:
    environment: TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i
        working-directory: server/orchestrator
      - name: Check env
        run: echo ${{ secrets.REDIS_HOST }}
      - name: Run unit tests using nyc and Mocha
        run: REDIS_HOST=${{ secrets.REDIS_HOST }} REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} REDIS_PORT=${{ secrets.REDIS_PORT }} REDIS_USERNAME=${{ secrets.REDIS_USERNAME }} npm test
        working-directory: server/orchestrator
  test-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i
        working-directory: server/services/user
      - name: Run unit tests using nyc and Mocha
        run: npm test
        working-directory: server/services/user
