name: Test

on:
  push:
    branches:
      - backend/01-initialize
  pull_request:
    branches:
      - main
      - backend/01-initialize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.13
    - name: Install dependencies
      run: npm i
      working-directory: server/user
    - name: Run unit tests using Mocha
      run: npm test -- --reporter=spec --testPathPattern='mocha tests/**/*.test.js' --exit
      working-directory: server/user
